env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.github/linters/tsconfig.json'
    - './tsconfig.json'

plugins:
  - jest
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:jest/recommended

rules:
  'i18n-text/no-en': off
  'import/no-namespace': off
