name: rtx action
description: Actions for working with rtx runtime manager
author: Jeff Dickey <@jdx>
branding:
  icon: arrow-down-circle
  color: purple
inputs:
  version:
    required: false
    description: The version of rtx to use. If not specified, will use the latest release.
  rtx_dir:
    required: false
    description: |
      The directory that rtx will be installed to, defaults to $HOME/.local/share/rtx
      Or $XDG_DATA_HOME/rtx if $XDG_DATA_HOME is set.
      Or $RTX_DATA_DIR if $RTX_DATA_DIR is set.
  tool_versions:
    required: false
    description: If present, this value will be written to the .tool-versions file
  rtx_toml:
    required: false
    description: If present, this value will be written to the .rtx.toml file
  install:
    required: false
    default: "true"
    description: if false, will not run `rtx install`
  install_dir:
    required: false
    default: "."
    description: The directory that `rtx install` will be executed in
  cache:
    required: false
    default: "true"
    description: if false, action will not read or write to cache
  cache_save:
    required: false
    default: "true"
    description: if false, action will not write to cache
  cache_key_prefix:
    required: false
    default: "rtx-v0"
    description: The prefix key to use for the cache, change this to invalidate the cache
  experimental:
    required: false
    default: "false"
    description: if true, will use experimental features
outputs:
  cache-hit:
    description: A boolean value to indicate if a cache was hit.
runs:
  using: node20
  main: dist/index.js
  post: dist/cache-save/index.js
  post-if: success()
