tasks.pre-commit = ["aubr all", "git add dist"]
tasks.test.alias = ["t"]
tasks.test.run = ["aubr all"]
tasks.lint = "aubr lint"
tasks."lint:fix" = "aubr format:write"
tasks.version = "aube version"
tasks.release-plz = "./scripts/release-plz.sh"

[tools]
node = '24'
aube = 'v1.5.1'
git-cliff = 'latest'
gh = 'latest'
communique = 'latest'
