name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4

      - name: Install dependencies
        run: aube ci

      - name: Build and package
        run: aubr all

      - name: autofix.ci
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1
